# Build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["src/Elisal.WasteManagement.UI/Elisal.WasteManagement.UI.csproj", "Elisal.WasteManagement.UI/"]
COPY ["src/Elisal.WasteManagement.Domain/Elisal.WasteManagement.Domain.csproj", "Elisal.WasteManagement.Domain/"]
COPY ["src/Elisal.WasteManagement.Application/Elisal.WasteManagement.Application.csproj", "Elisal.WasteManagement.Application/"]
RUN dotnet restore "Elisal.WasteManagement.UI/Elisal.WasteManagement.UI.csproj"
COPY ["src/", "./"]
WORKDIR "/src/Elisal.WasteManagement.UI"
RUN dotnet publish "Elisal.WasteManagement.UI.csproj" \
    -c Release \
    -p:WasmApplicationEnvironmentName=Development \
    -o /app/publish \
    --no-restore

# Runtime
FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=build /app/publish/wwwroot .
# 👇 Esta linha é a chave
COPY nginx.ui.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]